output_dir: '../../data/cd4/experiments'
module: src.experiments.image_seq_domain_translation
class: ImageSeqTranslationExperiment
run_params:
  image_data_config: {'image_dir':'../../data/cd4/nuclear_crops_all_experiments/128px/labeled_scaled_max_intensity_resized_images',
                      'label_fname':'../../data/cd4/nuclear_crops_all_experiments/simple_image_labels.csv',
                      'data_key':'image', 'label_key':'label'}

  image_model_config: {'model_config':{'type':'VanillaConvVAE', 'latent_dim':256, 'hidden_dims':[128, 256, 512, 1024, 1024]},
                       'optimizer_config':{'type':'adam','lr':0.0001},
                       'loss_config':{'type':'mse'}}

  seq_data_config: {'data_fname':'../../data/cd4/cd4_rna_seq_pbmc_10k/gene_kegg_pathway_data_and_labels.csv', 'data_key':'seq_data',
                    'label_key':'label'}

  seq_model_config : {'model_config':{'type':'GeneSetVAE',
                                      'geneset_adjacencies_file':'../../data/cd4/cd4_rna_seq_pbmc_10k/gene_kegg_pathway_adj_filtered_nCD4.csv',
                                      'input_dim':5785, 'latent_dim':256, 'hidden_dims':[512, 512, 512]
                                      },
                      'optimizer_config':{'type':'adam', 'lr':0.0001},
                      'loss_config':{'type':'mse'}}

  latent_dcm_config: {'model_config':{'type':'LatentDiscriminator', 'latent_dim':256, 'n_classes':2},
                      'optimizer_config':{'type':'adam', 'lr':0.0001},
                      'loss_config':{'type':'ce','weights':[1.0, 2.75]}}

  latent_structure_model_config: {'model_config': { 'type': 'LatentClassifier', 'latent_dim': 256, 'n_classes': 2 },
                                   'optimizer_config': { 'type': 'adam', 'lr': 0.0001 },
                                   'loss_config': {'type': 'ce', 'weights':[2.5,1.0]}}

  num_epochs: 1000
  early_stopping: -1
  train_val_test_split: [0.6, 0.2, 0.2]
  batch_size: 8
  random_state: 42


pipeline:
  - method: initialize_image_data_set
  - method: initialize_seq_data_set
  - method: initialize_image_data_loader_dict
  - method: initialize_seq_data_loader_dict
  - method: initialize_image_domain_config
  - method: initialize_seq_domain_config
  - method: initialize_clf_model
  - method: initialize_dcm_model
  - method: train_models
    params:
      alpha: 0.1
      beta: 1.0
      save_freq: 50
      use_latent_discriminator: True
      use_latent_structure_model: True


