output_dir: '../../data/a549/experiments'
module: src.experiments.model_pretraining
class: PretrainAeExperiment
run_params:
  data_config: {'data_fname':'../../data/a549_dex/processed/rna_data.csv',
                      'data_key':'seq_data', 'label_key':'label'}

  model_config : {'model_config':{'type':'VanillaAE',
                        'hidden_dims':[4096, 4096, 4096, 4096, 4096, 4096, 4096, 128],
                        'latent_dim': 50,
                        'input_dim':2613},
                        'optimizer_config':{'type':'adam', 'lr':0.0001, 'weight_decay':0.000},
                        'loss_config':{'type':'mae'}}

  latent_structure_model_config: {'model_config':{'type':'LatentClassifier', 'latent_dim':50, 'n_classes':3},
                      'optimizer_config':{'type':'adam', 'lr':0.0001},
                      'loss_config':{'type':'ce',}}

  domain_name: 'rna'
  num_epochs: 10000
  early_stopping: -1
  train_val_test_split: [0.6, 0.2, 0.2]
  batch_size: 32
  random_state: 1234


pipeline:
  - method: initialize_seq_data_set
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: initialize_clf_model
  #- method: load_model
  #  params:
  #    weights_fname: '../../data/experiments/20200805_134219/best_vae.pth'
  - method: train_models
    params:
      alpha: 1.0
      gamma: 0.0
      save_freq: 1000
      use_latent_structure_model: False

