output_dir: '../../data/cd4/experiments'
module: src.experiments.model_pretraining
class: PretrainAeExperiment
run_params:
  data_config: {'image_dir':'../../data/cd4/nuclear_crops_all_experiments/128px/labeled_scaled_max_intensity_resized_images',
                      'label_fname':'../../data/cd4/nuclear_crops_all_experiments/simple_image_labels.csv',
                      'data_key':'image', 'label_key':'label'}

  model_config: {'model_config':{'type':'VanillaConvAE', 'latent_dim':256},
                       'optimizer_config':{'type':'adam','lr':0.001},
                       'loss_config':{'type':'mse'}}

  latent_structure_model_config: {'model_config':{'type':'LatentClassifier', 'latent_dim':256, 'n_classes':2},
                      'optimizer_config':{'type':'adam', 'lr':0.001},
                      'loss_config':{'type':'ce', 'weights':[4.5,0.5]}}

  domain_name: 'image'
  num_epochs: 1000
  early_stopping: 100
  train_val_test_split: [0.7, 0.2, 0.1]
  batch_size: 16
  random_state: 1234


pipeline:
  - method: initialize_image_data_set
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: initialize_clf_model
  - method: train_models
    params:
      gamma: 0.0
      save_freq: 1
      use_latent_structure_model: True

